kind: Config
apiVersion: v1
preferences:
  colors: true

clusters:
- name: secure
  cluster:
    server: {APISERVER}
    api-version: v1
    insecure-skip-tls-verify: false
    certificate-authority: ./cert/ca/apiserver/ca.pem

users:
- name: {NAME}
  user:
    client-certificate: ./cert/apiserver-client/cert.pem
    client-key: ./cert/apiserver-client/key.pem

contexts:
- name: secure.{NAME}.default
  context:
    cluster: secure
    user: {NAME}
    namespace: default

current-context: secure.{NAME}.default
